### ISSUE TITLE
Benchmark speed of Pydantic 2.9 (perhaps using uvtrick)

### ISSUE THREAD

**Issue by lmmx** [lmmx/emptypt#4]
"35% faster import times" and "up to 10x faster schema building": put a benchmark on this using `emptypt` and `uvtrick`

**Source**: - [Pydantic v2.9][blog] (release blog [via][li] Sydney Runkle, LinkedIn)

[blog]: https://pydantic.dev/articles/pydantic-v2-9-release
[li]: https://www.linkedin.com/posts/sydney-runkle_pydantic-v29-pydantic-activity-7237508833344991233-Iiya

> Decrease pydantic import times by ~35%, see [#10009](https://github.com/pydantic/pydantic/pull/10009) This covers cases like import pydantic and from pydantic import BaseModel

> Speed up schema building (and memory allocations) by up to 10x by skipping namespace caches, see [#10113](https://github.com/pydantic/pydantic/pull/10113)

**Comment by lmmx** [comment]
No change...

```
(emptypt) louis 🌟 ~/dev/emptypt $ uv pip install pydantic==2.8
Resolved 4 packages in 133ms
Prepared 2 packages in 245ms
Uninstalled 2 packages in 2ms
Installed 2 packages in 3ms
 - pydantic==2.9.0
 + pydantic==2.8.0
 - pydantic-core==2.23.2
 + pydantic-core==2.20.0
(emptypt) louis 🌟 ~/dev/emptypt $ qp benchmark_entrypoints.py 
```

| Rank   |               Configuration | Execution Time   |      entrypoint       | Autogenerate from config   |
|:-------|----------------------------:|:-----------------|:---------------------:|:---------------------------|
| 1      |  Stdlib [baseline], minimum | 0.016s           |    emptypt-minimum    | -                          |
| 2      |   Stdlib [baseline], simple | 0.016s           |    emptypt-simple     | -                          |
| 3      |              msgspec + argh | 0.059s           |    emptypt-m-argh     | Yes                        |
| 4      |  msgspec + argh (docstring) | 0.060s           | emptypt-m-argh-docstr | Yes                        |
| 5      |             msgspec + click | 0.073s           |    emptypt-m-click    | -                          |
| 6      |             pydantic + argh | 0.161s           |    emptypt-p-argh     | Yes                        |
| 7      | pydantic + argh (docstring) | 0.162s           | emptypt-p-argh-docstr | Yes                        |
| 8      |            msgspec + defopt | 0.169s           |   emptypt-m-defopt    | Yes                        |
| 9      |            pydantic + click | 0.184s           |    emptypt-p-click    | -                          |
| 10     |             msgspec + typer | 0.229s           |    emptypt-m-typer    | -                          |
| 11     |           pydantic + defopt | 0.251s           |   emptypt-p-defopt    | Yes                        |
| 12     |            pydantic + typer | 0.315s           |    emptypt-p-typer    | -                          |

```
(emptypt) louis 🌟 ~/dev/emptypt $ uv pip install pydantic==2.9
Resolved 5 packages in 21ms
Uninstalled 2 packages in 1ms
Installed 2 packages in 2ms
 - pydantic==2.8.0
 + pydantic==2.9.0
 - pydantic-core==2.20.0
 + pydantic-core==2.23.2
(emptypt) louis 🌟 ~/dev/emptypt $ qp benchmark_entrypoints.py 
```

| Rank   |               Configuration | Execution Time   |      entrypoint       | Autogenerate from config   |
|:-------|----------------------------:|:-----------------|:---------------------:|:---------------------------|
| 1      |   Stdlib [baseline], simple | 0.015s           |    emptypt-simple     | -                          |
| 2      |  Stdlib [baseline], minimum | 0.016s           |    emptypt-minimum    | -                          |
| 3      |  msgspec + argh (docstring) | 0.059s           | emptypt-m-argh-docstr | Yes                        |
| 4      |              msgspec + argh | 0.060s           |    emptypt-m-argh     | Yes                        |
| 5      |             msgspec + click | 0.073s           |    emptypt-m-click    | -                          |
| 6      |             pydantic + argh | 0.165s           |    emptypt-p-argh     | Yes                        |
| 7      |            msgspec + defopt | 0.166s           |   emptypt-m-defopt    | Yes                        |
| 8      | pydantic + argh (docstring) | 0.166s           | emptypt-p-argh-docstr | Yes                        |
| 9      |            pydantic + click | 0.188s           |    emptypt-p-click    | -                          |
| 10     |             msgspec + typer | 0.226s           |    emptypt-m-typer    | -                          |
| 11     |           pydantic + defopt | 0.259s           |   emptypt-p-defopt    | Yes                        |
| 12     |            pydantic + typer | 0.331s           |    emptypt-p-typer    | -                          |

**Comment by sydney-runkle** [comment]
Hmm - I'm not surprised to see that schema build times haven't changed for some folks - those changes were aimed at improving build times for modules with lots of models / a very large namespace.

That being said, I'm surprised to not see import times decrease...

We based the 35% metric on this: https://codspeed.io/pydantic/pydantic/runs/66aa9867096947f745c9ce5f.

Happy to look into this further - thanks for reporting your stats here!

**Comment by lmmx** [comment]
Oh I didn't expect this to be raised by someone else on the official repo haha, I just wanted to see if this affected this existing repro, which in turn was to get an intuition on ideal case CLI latency factors

I figured as much RE: multi model impact. As the name suggests this is only a minimal ('empty') use of an entrypoint parsing CLI inputs into either a msgspec Struct/Pydantic model.

It's primarily to gauge the best case scenario and essentially to record the pattern of CLI from data structures, including help messages from docstrings in each framework. The new Pydantic field description from docstring feature is a big readability improvement on that front
